services:
  db:
    image: postgres:15-alpine
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend

  admin:
    build:
      context: ./admin
    depends_on:
      - backend

volumes:
  postgres_data:
